name: power_she_pre
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  google_fonts: ^3.0.1
  persistent_bottom_nav_bar_v2: ^4.2.6
  custom_line_indicator_bottom_navbar: ^0.0.8
  curved_nav_bar: ^0.0.2
  sidebarx: ^0.14.0
  firebase_database: ^10.0.9
  url_launcher: ^6.1.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_carousel_intro: ^0.0.9

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - images/
    - assets/
  
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Lustria
      fonts:
        - asset: fonts/Lustria-Regular.ttf
